name: Nightly Karate Tests

on:
  schedule:
    - cron: '0 0 * * *'  # Runs at 1 AM CET
  workflow_dispatch:  # Allows manual triggering of the workflow

jobs:
  run-karate-tests:
    runs-on: ubuntu-latest
    environment: dev  # Specify your environment name here if you need to target a specific environment for secrets

    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'

    - name: Install Maven
      run: |
        sudo apt-get update
        sudo apt-get install -y maven

    - name: Run Karate Tests
      run: mvn clean test
      env:  # Set environment variables from GitHub secrets here
        AUTH_URL: ${{ secrets.AUTHURL }}
        SENSOR_URL: ${{ secrets.SENSORURL }}
        VERIFICATION_URL: ${{ secrets.VERIFICATIONURL }}
        API_KEY: ${{ secrets.APIKEY }}

    - name: Zip Cucumber Reports
      run: zip -r cucumber-reports.zip target/cucumber-html-reports

    - name: Upload Cucumber Reports
      uses: actions/upload-artifact@v2
      with:
        name: cucumber-reports
        path: cucumber-reports.zip