name: Nightly Karate Tests

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  run-karate-tests:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install Maven
      run: |
        sudo apt-get update
        sudo apt-get install -y maven

    - name: Install Node.js Dependencies
      run: npm install

    - name: Run Karate Tests
      run: npm run karate:run:project
      env:
        AUTHURL: ${{ secrets.AUTHURL }}
        SENSORURL: ${{ secrets.SENSORURL }}
        VERIFICATIONURL: ${{ secrets.VERIFICATIONURL }}
        APIKEY: ${{ secrets.APIKEY }}

    - name: Zip Cucumber Reports
      run: zip -r cucumber-reports.zip target/cucumber-html-reports

    - name: Upload Cucumber Reports
      uses: actions/upload-artifact@v2
      with:
        name: cucumber-reports
        path: cucumber-reports.zip
