name: Automated Nightly Runs

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:  

jobs:
  run-karate-tests:
    runs-on: ubuntu-latest  # Specify the runner

    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'

    - name: Install Maven
      run: |
        sudo apt-get update
        sudo apt-get install -y maven

    - name: Run Karate Tests
      run: mvn clean test
